version: "3"
services:
  postgresql:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: test
    ports:
      - 15432:5432
    volumes:
      - postgres/init.d:/docker-entrypoint-initdb.d

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 13306:3306
    volumes:
      - postgres/init.d:/docker-entrypoint-initdb.d